name: first-workflow
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        uses: actions/checkout@v3
      - run: echo "First Job Step First"        
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        uses: actions/checkout@v3
      - run: echo "Second Job Step First"  
        
